import { type NextPage } from "next";
import Head from "next/head";
import ThemeSwitcher from "y/components/ThemeSwitcher";
import Todo from "y/components/Todo";

import { api } from "y/utils/api";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Todo - T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen justify-center bg-gray-200 p-7  transition-all dark:bg-gray-800 dark:text-gray-200">
        <Todo />
        <ThemeSwitcher />
      </main>
    </>
  );
};

export default Home;
